# 記述統計量

- 1963年から2020年までの年次データを用いて、厚生変化を記述する

```{r}
library(tidyverse)
library(readxl)
```

```{r}
col.label <- 
   c("year",
     "n",
     "type",
     "group")

raw.vacancy.full <-
  read_excel("data/第6表.xlsx",
             sheet = "第６表ー２（パート除く）") %>%
  .[14:62,c(1,20)] %>%
  mutate(type = "求人",
         group = "フルタイム")

colnames(raw.vacancy.full) <- col.label

raw.seeker.full <-
  read_excel("data/第7表.xlsx",
             sheet = "第７表ー２（パート除く）") %>%
  .[14:62,c(1,20)] %>%
  mutate(type = "求職",
         group = "フルタイム")

colnames(raw.seeker.full) <- col.label

raw.hir.full <-
  read_excel("data/第8表.xlsx",
             sheet = "第８表ー２（パート除く）") %>%
  .[14:62,c(1,20)] %>%
  mutate(type = "新規就職",
         group = "フルタイム")

colnames(raw.hir.full) <- col.label


raw.vacancy.part <-
  read_excel("data/第6表.xlsx",
             sheet = "第６表ー３（パート）") %>%
  .[14:62,c(1,20)] %>%
  mutate(type = "求人",
         group = "パートタイム")

colnames(raw.vacancy.part) <- col.label

raw.seeker.part <-
  read_excel("data/第7表.xlsx",
             sheet = "第７表ー３（パート）") %>%
  .[14:62,c(1,20)] %>%
  mutate(type = "求職",
         group = "パートタイム")

colnames(raw.seeker.part) <- col.label

raw.hir.part <-
  read_excel("data/第8表.xlsx",
             sheet = "第８表ー３（パート）") %>%
  .[14:62,c(1,20)] %>%
  mutate(type = "新規就職",
         group = "パートタイム")

colnames(raw.hir.part) <- col.label

df <-
  rbind(raw.hir.full,
        raw.hir.part,
        raw.vacancy.full,
        raw.vacancy.part,
        raw.seeker.full,
        raw.seeker.part) %>%
  mutate(n = as.numeric(n),
         year = as.numeric(str_sub(year,1,4))) %>%
  spread(type,
         value = n) %>%
  mutate(求人倍率 = 求人/求職,
         充足率 = 新規就職/求人,
         入職率 = 新規就職/求職) %>%
  arrange(group,
          year) %>%
  group_by(group) %>%
  mutate(サーチ余剰変化 = log(求人倍率) - log(lag(求人倍率)),
         入職率変化 = log(入職率) - log(lag(入職率)),
         マッチング余剰変化 = log(lag(充足率)) - log(充足率)
         ) %>%
  ungroup
```

- 就職件数の推移

```{r}
df %>%
  gather(新規就職,
         key = "要素",
         value = "件数"
         ) %>%
  ggplot(aes(x = year,
             y = 件数,
             color = 要素)
         ) +
  geom_line() +
  geom_point() +
  facet_wrap(~group) +
  theme_bw() +
  ylab("") +
  xlab("") +
  theme(legend.position = "bottom")
```

- 求人、求職件数の推移

```{r}
df %>%
  gather(求人,
         求職,
         key = "要素",
         value = "件数"
         ) %>%
  ggplot(aes(x = year,
             y = 件数,
             color = 要素)
         ) +
  geom_line() +
  geom_point() +
  facet_wrap(~ group) +
  theme_bw() +
  theme(legend.position = "bottom")
```

- 入職。充足率の推移

```{r}
df %>%
  gather(充足率,
         入職率,
         key = "要素",
         value = "率"
         ) %>%
  ggplot(aes(x = year,
             y = 率,
             color = 要素)
         ) +
  geom_line() +
  geom_point() +
  facet_wrap(~ group) +
  theme_bw() +
  theme(legend.position = "bottom")
```
