# 厚生分析:長期時系列

- 1963年から2020年までの年次データを用いて、厚生変化を記述する

## 方法

- @kawata2021first の手法を用いて、失業者の厚生変化を記述する

- 標準的なDiamond-Mortencen-Pissarides型サーチモデル[@rogerson2005search]に準じて、以下の4条件式を仮定する

1. 失業者の価値観数

$$rU_i=b+\dot{U}_i+\underbrace{\Delta_i}_{総余剰}$$

$$\Delta_i = \sum_j\frac{m_{ij}}{u_i}\times (W_{ij}-U_i)$$

2. 求人の価値観数

$$rV_j=k+\dot{V}_j+\sum_{i}\frac{m_{ij}}{v_j}\times (J_{ij}-V_j)$$

3. 自由参入条件

$$V_j=\dot{V}_j=0$$

4. ナッシュ交渉

$$(1-\beta)(W_{ij}-U_i)=\beta(J_{ij}-V_j)$$

- 以上の4条件から総余剰の平均値は以下のように書き換えられる

$$E[\Delta_i]=\sum u_i\Delta_i=\underbrace{\frac{\sum_{ij}m_{ij}}{\sum_i u_i}}_{入職率}\times\underbrace{\frac{\beta k}{1-\beta}\times\frac{\sum_{j}v_j}{\sum_{ij}m_{ij}}}_{マッチングの余剰}$$

## Rコード

```{r}
col.label <- 
   c("year",
     "1",
     "2",
     "3",
     "4",
     "5",
     "6",
     "7",
     "8",
     "9",
     "10",
     "11",
     "12",
     "type",
     "group")

select.raw <- 14:63

select.column <- c(1,3:14)

raw.vacancy.full <-
  read_excel("data/第6表.xlsx",
             sheet = "第６表ー２（パート除く）") %>%
  .[select.raw,select.column] |> 
  mutate(type = "求人",
         group = "フルタイム")

colnames(raw.vacancy.full) <- col.label

raw.seeker.full <-
  read_excel("data/第7表.xlsx",
             sheet = "第７表ー２（パート除く）") %>%
  .[select.raw,select.column] |> 
  mutate(type = "求職",
         group = "フルタイム")

colnames(raw.seeker.full) <- col.label

raw.hir.full <-
  read_excel("data/第8表.xlsx",
             sheet = "第８表ー２（パート除く）") %>%
  .[select.raw,select.column] |> 
  mutate(type = "新規就職",
         group = "フルタイム")

colnames(raw.hir.full) <- col.label


raw.vacancy.part <-
  read_excel("data/第6表.xlsx",
             sheet = "第６表ー３（パート）") %>%
  .[select.raw,select.column] |> 
  mutate(type = "求人",
         group = "パートタイム")

colnames(raw.vacancy.part) <- col.label

raw.seeker.part <-
  read_excel("data/第7表.xlsx",
             sheet = "第７表ー３（パート）") %>%
  .[select.raw,select.column] |> 
  mutate(type = "求職",
         group = "パートタイム")

colnames(raw.seeker.part) <- col.label

raw.hir.part <-
  read_excel("data/第8表.xlsx",
             sheet = "第８表ー３（パート）") %>%
  .[select.raw,select.column] |> 
  mutate(type = "新規就職",
         group = "パートタイム")

colnames(raw.hir.part) <- col.label

df <-
  rbind(raw.hir.full,
        raw.hir.part,
        raw.vacancy.full,
        raw.vacancy.part,
        raw.seeker.full,
        raw.seeker.part
        ) |> 
  pivot_longer(cols = 2:13,
               names_to = "month",
               values_to = "n") |> 
  mutate(n = n |> as.numeric(),
         year = year |> str_sub(1,4) |> as.numeric(),
         month = month |> as.numeric(),
         quaterly = month |> cut(c(0,3,6,9,12), labels = c(1,2,3,4)),
         date = yq(str_c(year,quaterly,sep = ":Q"))
         ) |> 
  group_by(date,type) |> 
  mutate(n = n |> sum()) |> 
  ungroup() |> 
  distinct(year,quaterly,date,type,n) |> 
  spread(key = type, value = n) |> 
  group_by(quaterly) |> 
  mutate(入職率 = log(新規就職/求職) - log(lag(新規就職/求職)),
        　マッチングの余剰 = log(lag(新規就職/求人)) - log(新規就職/求人),
           総余剰 = log(求人/求職) - log(lag(求人/求職))
           ) |> 
  ungroup() |> 
  select(-求職,
         -求人,
         -新規就職) |> 
  pivot_longer(cols = c(4:6),
               names_to = "type",
               values_to = "N") |> 
  na.omit()

fig <-
  df |> 
  ggplot(aes(x = date,
             y = N)
         ) +
  geom_line() +
  geom_hline(yintercept = 0) +
  facet_wrap(~factor(type,
                     levels = c("マッチングの余剰",
                                "入職率",
                                "総余剰")),
             ncol = 1) +
  ylab("") +
  xlab("") +
  theme_bw()
```

## 結果

```{r, echo = FALSE}
fig
```

