---
title: "R Notebook"
output: 
  html_notebook: 
    number_sections: yes
---

# Decomposition

The matching function is

$$h_{j,t}=A_{j,t}\times v_{j,t}^{\alpha}\times u_{j,t}^{1-\alpha}.$$

The optimal allocation is

$$u_{j,t}^*=\frac{A_{j,t}^{1/\alpha}v_{j,t}}{\sum_{j'}A_{j',t}^{1/\alpha}v_{j',t}}u_{t},$$

and the job production is

$$h_{j,t}^*=A_{j,t}v_{j,t}^{\alpha}\times \frac{A_{j,t}^{1-\alpha/\alpha}v_{j,t}^{1-\alpha}}{\sum_{j'}A_{j',t}^{1/\alpha}v_{j',t}}u_{t}^{1-\alpha}.$$


$$=A_{j,t}^{1/\alpha}v_{j,t}\times \frac{1}{[\sum_{j'}A_{j',t}^{1/\alpha}v_{j',t}]^{1-\alpha}}u_{t}^{1-\alpha}$$

The aggregate production is

$$h_t^*=\sum h_{j,t}^*=\tilde{A}_t\times v_{t}^{\alpha}\times u_{t}^{1-\alpha}$$

where

$$\tilde A_{t}=[\sum_{j'}A_{j',t}^{1/\alpha}\times \frac{v_{j',t}}{v_t}]^{\alpha}.$$

The job finding rate can be decomposed as

$$\log\frac{p_t}{p_{t-12}}=\log m_t+\log h_t^* - \log m_{t-12} -\log h^*_{t-12}$$

$$=\underbrace{\log m_t - \log m_{t-12}}_{Mismatch}$$

$$+\underbrace{\log \tilde A_t-\log \tilde A_{t-12}}_{Efficiency}$$

$$+\underbrace{\alpha[\log v_t - \log v_{t-12}}_{Vacancy}]$$

$$-\underbrace{\alpha[\log u_t - \log u_{t-12}}_{Seeker}]$$

# Environment

```{r environment}
library(readxl)
library(tidyverse)
library(lubridate)
```

# Data import

```{r}
year <- c(rep(2012,10),
          rep(2013,12),
          rep(2014,12),
          rep(2015,12),
          rep(2016,12),
          rep(2017,12),
          rep(2018,12),
          rep(2019,12),
          rep(2020,12),
          rep(2021,3)
)

month <- c(c(3:12),
           rep(1:12,8),
           c(1:3))
```


## Occupation

```{r grobal occupation}
occ <- c("Management",
         "Technical specialist",
         "Office",
         "Sales",
         "Service",
         "Security",
         "Agriculture, Forestry, and Fisheries",
         "Production process",
         "Driver",
         "Construction and Mining",
         "Others")

sel.raw <- c(5,6,19,27,31,40,41,42,54,60,66)

sel.col <- c(19:127)

```

### Full time

```{r full time occupation}
raw.new.vac <- read_excel("C:/Users/kawata/Dropbox/data/RPPERS/第21表.xlsx",
                  sheet = "第２１表ー８　 新規求人（パート除く常用）")
raw.vac <- read_excel("C:/Users/kawata/Dropbox/data/RPPERS/第21表.xlsx",
                  sheet = "第２１表ー９　有効求人（パート除く常用）")
raw.new.see <- read_excel("C:/Users/kawata/Dropbox/data/RPPERS/第21表.xlsx",
                  sheet = "第２１表ー１０　新規求職（パート除く常用）")
raw.see <- read_excel("C:/Users/kawata/Dropbox/data/RPPERS/第21表.xlsx",
                      sheet = "第２１表ー１１　有効求職（パート除く常用）")
raw.hir <- read_excel("C:/Users/kawata/Dropbox/data/RPPERS/第21表.xlsx",
                      sheet = "第２１表ー１２　就職件数（パート除く常用）")

#####
raw <- raw.new.vac[sel.raw,sel.col] %>%
  mutate(occ = occ)

name <- names(raw)[-ncol(raw)]

df.new.vac <- gather(raw,
                     name,
                     key = "date", 
                     value = "n") %>%
  group_by(occ) %>%
  mutate(year = year,
         month = month,
         type = "New Vacancy")

#####
raw <- raw.new.see[sel.raw,sel.col] %>%
  mutate(occ = occ)

name <- names(raw)[-ncol(raw)]

df.new.see <- gather(raw,
               name,
         key = "date", 
         value = "n") %>%
  group_by(occ) %>%
  mutate(year = year,
         month = month,
         type = "New Seeker")

#####
raw <- raw.vac[sel.raw,sel.col] %>%
  mutate(occ = occ)

name <- names(raw)[-ncol(raw)]

df.vac <- gather(raw,
               name,
         key = "date", 
         value = "n") %>%
  group_by(occ) %>%
  mutate(year = year,
         month = month,
         type = "Vacancy")

#####
raw <- raw.see[sel.raw,sel.col] %>%
  mutate(occ = occ)

name <- names(raw)[-ncol(raw)]

df.see <- gather(raw,
                 name,
                 key = "date", 
                 value = "n") %>%
  group_by(occ) %>%
  mutate(year = year,
         month = month,
         type = "Seeker")

#####
raw <- raw.hir[sel.raw,sel.col] %>%
  mutate(occ = occ)

name <- names(raw)[-ncol(raw)]

df.hir <- gather(raw,
                 name,
                 key = "date", 
                 value = "n") %>%
  group_by(occ) %>%
  mutate(year = year,
         month = month,
         type = "Hir")

raw.full <- 
  rbind(df.see,
        df.hir,
        df.vac,
        df.new.see,
        df.new.vac
        ) %>%
  mutate(date = make_date(year, month),
         n = as.numeric(n),
         job_type = "Full-time")
```

### Part time

```{r part time occupation}
raw.new.vac <- read_excel("C:/Users/kawata/Dropbox/data/RPPERS/第21表.xlsx",
                      sheet = "第２１表ー１５　新規求人（常用的パート）")
raw.vac <- read_excel("C:/Users/kawata/Dropbox/data/RPPERS/第21表.xlsx",
                      sheet = "第２１表ー１６　有効求人（常用的パート）")
raw.new.see <- read_excel("C:/Users/kawata/Dropbox/data/RPPERS/第21表.xlsx",
                      sheet = "第２１表ー１７　新規求職（常用的パート）")
raw.see <- read_excel("C:/Users/kawata/Dropbox/data/RPPERS/第21表.xlsx",
                      sheet = "第２１表ー１８　有効求職（常用的パート）")
raw.hir <- read_excel("C:/Users/kawata/Dropbox/data/RPPERS/第21表.xlsx",
                      sheet = "第２１表ー１９　就職件数（常用的パート）")

#####

raw <- raw.new.vac[sel.raw,sel.col] %>%
  mutate(occ = occ)

name <- names(raw)[-ncol(raw)]

df.new.vac <- gather(raw,
               name,
         key = "date", 
         value = "n") %>%
  group_by(occ) %>%
  mutate(year = year,
         month = month,
         type = "New Vacancy")

#####

raw <- raw.new.see[sel.raw,sel.col] %>%
  mutate(occ = occ)

name <- names(raw)[-ncol(raw)]

df.new.see <- gather(raw,
               name,
         key = "date", 
         value = "n") %>%
  group_by(occ) %>%
  mutate(year = year,
         month = month,
         type = "New Seeker")

#####

raw <- raw.vac[sel.raw,sel.col] %>%
  mutate(occ = occ)

name <- names(raw)[-ncol(raw)]

df.vac <- gather(raw,
               name,
         key = "date", 
         value = "n") %>%
  group_by(occ) %>%
  mutate(year = year,
         month = month,
         type = "Vacancy")


#####

raw <- raw.vac[sel.raw,sel.col] %>%
  mutate(occ = occ)

name <- names(raw)[-ncol(raw)]

df.vac <- gather(raw,
               name,
         key = "date", 
         value = "n") %>%
  group_by(occ) %>%
  mutate(year = year,
         month = month,
         type = "Vacancy")

#####
raw <- raw.see[sel.raw,sel.col] %>%
  mutate(occ = occ)

name <- names(raw)[-ncol(raw)]

df.see <- gather(raw,
                 name,
                 key = "date", 
                 value = "n") %>%
  group_by(occ) %>%
  mutate(year = year,
         month = month,
         type = "Seeker")

#####
raw <- raw.hir[sel.raw,sel.col] %>%
  mutate(occ = occ)

name <- names(raw)[-ncol(raw)]

df.hir <- gather(raw,
                 name,
                 key = "date", 
                 value = "n") %>%
  group_by(occ) %>%
  mutate(year = year,
         month = month,
         type = "Hir")

raw.part <- 
  rbind(df.see,
        df.hir,
        df.vac,
        df.new.vac,
        df.new.see
        ) %>%
  mutate(date = make_date(year, month),
         n = as.numeric(n),
         job_type = "Part-time")
```

### Merge

```{r merge occupation}
df.occ <-
  raw.full %>%
  rbind(raw.part) %>%
  spread(type,n) %>%
  mutate(p = Hir/Seeker,
         q = Hir/Vacancy,
         t = Vacancy/Seeker,
         date = make_date(year, month))
```

# Estimation

Suppose a matching function as

$$p_{jt} = A_{jt}\theta_{jt}^{\eta}$$

## Occupation

```{r estimation occupation}
eta.full <- 
  df.occ %>%
  filter(job_type == "Full-time") %>%
  filter(occ != "Others") %>%
  lm(log(p) ~ log(t) + factor(occ) + factor(month) + factor(year),
     data =.) %>%
  coef %>%
  .[2]

eta.part <- 
  df.occ %>%
  filter(job_type == "Part-time") %>%
  filter(occ != "Others") %>%
  lm(log(p) ~ log(t) + factor(occ) + factor(month) + factor(year),
     data =.) %>%
  coef %>%
  .[2]

result.occ <-
  df.occ %>%
  filter(occ != "Others") %>%
  mutate(eta = if_else(job_type == "Full-time",
                       eta.full,
                       eta.part
                       ),
         A = p/(t^eta),
         weight = (A^(1/eta))*Vacancy
         )  %>%
  group_by(job_type,
           date) %>%
  mutate(weight = weight/sum(weight),
         Optimal.Seeker = weight*sum(Seeker),
         Optimal.Hir = A*(Vacancy^(eta))*(Optimal.Seeker^(1-eta)),
         Optimal.Agg.Hir = sum(Optimal.Hir),
         Agg.Hir = sum(Hir),
         Agg.Mismatch = (Optimal.Agg.Hir - Agg.Hir)/Agg.Hir) %>%
  ungroup
```

# Visualization

```{r}
fig <-
  result.occ %>%
  distinct(Agg.Mismatch,
           job_type,
           date) %>%
  ggplot(aes(x = date,
             y = Agg.Mismatch)
         ) +
  geom_line() +
  facet_wrap(~job_type,
             scale = "free",
             ncol = 1) +
  theme_bw() +
  ylab("Mismatch Index")

fig

ggsave("figure/occ_mismatch.png",
       plot = fig,
       dpi = "retina")
```

